---
# Secret for MySQL credentials
apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: dev
type: Opaque
stringData:
  mysql-host: "192.168.56.7"
  mysql-port: "3306"
  mysql-database: "appdb"
  mysql-user: "phpuser"
  mysql-password: "PhpPass123!"